# @package _group_

name: resnext101_32x8d
ckpt_path: ${path.model}/imagenetr_models/resnext101_augmix_and_deepaugment.pth.tar
imagenet_subset: True
num_classes: ${network.num_classes}
group: imagenet
