# @package _group_

name: resnext101_32x8d
ckpt_path: ${path.model}/imagenetr_models/resnext101_augmix_and_deepaugment.pth.tar
imagenet_subset_path: ${datamodule.root}/train
imagenet_path: ${path.imagenet1000}/train
num_classes: ${network.num_classes}
group: imagenet
