# @package _group_

name: resnext101_32x8d
ckpt_path: /work/dlclarge2/agnihotr-shashank-pruneshift/teachers/img100/amda_resnext101_32x8d/checkpoint/last.ckpt
#imagenet_subset_path: ${datamodule.root}/train
num_classes: 100
group: imagenet
