# @package _group_

name: resnet34
ckpt_path: /work/dlclarge2/agnihotr-shashank-pruneshift/resnet34/standard/checkpoint/last.ckpt
#imagenet_subset_path: ${datamodule.root}/train
num_classes: 100
group: imagenet
