# @package _group_

name: resnet50
ckpt_path: /misc/lmbraid19/hoffmaja/models/imagenetr_models/deepaugment_and_augmix.pth.tar
imagenet_subset: True
num_classes: ${network.num_classes}
group: imagenet
