# @package _global_

datamodule:
    name: cifar100_augmix_corrupted
    root: ${path.dataset}
    num_workers: 10
    batch_size: 128
    no_jsd: False

network:
    num_classes: 100
    group: cifar

