# @package _global_

datamodule:
    name: imagenet
    root: ${path.imagenet100}
    deepaugment_path: ${path.deepaugment}
    num_workers: 6 
    test_corrupted: True
    test_renditions: True
    batch_size: 256

network:
    num_classes: 100
    group: imagenet

trainer:
    max_epochs: 5

scheduler:
    _target_: pruneshift.modules.cosine_lr
    T_max: ${trainer.max_epochs}

optimizer:
    lr: 0.1
