# @package _global_

datamodule:
    name: imagenet 
    root: ${path.imagenet1000}
    num_workers: 6
    test_corrupted: True
    test_renditions: ${path.renditions}
    batch_size: 256 

network:
    num_classes: 1000
    group: imagenet

scheduler:
    _target_: pruneshift.modules.multi_step_warm_up_lr
    warmup_end: 5
    milestones: [30, 60, 80]

trainer:
    max_epochs: 90

optimizer:
    lr: 0.1
