# @package _group_

_target_: pruneshift.losses.Augmix_CRD_Loss
alpha: 12.
kd_T: 4.
charlie: 0.1
delta: 0.8
feat_dim: 128
nce_k: 16384
nce_t: 0.07
nce_m: 0.5

teacher_model_id: cifar100_resnet18
teacher_path: "/misc/lmbraid19/agnihotr/thesis_pruneshift/2021-02-16/02-30-32/checkpoint/epoch_99.ckpt"

percent: 1.0
mode: 'exact'
k: 4096
