# @package _global_

loss:
  _target_: pruneshift.losses.ContrastiveDistill
  augmix_alpha: 12
  kd_T: 4.
  charlie: 0.0
  delta: 1.0
  beta: 1
  feat_dim: 128
  nce_k: 16384
  nce_t: 0.07
  nce_m: 0.5
  augmix: True

datamodule:
  augmix: True
  crd: True
