# @package _group_

_target_: pruneshift.losses.Augmix_KnowledgeDistill
alpha: 12.
beta: 0.1
kd_T: 4.
charlie: 0.9
teacher_path: "/misc/lmbraid19/agnihotr/thesis_pruneshift/2021-02-15/04-47-18/checkpoint/epoch_92.ckpt"
teacher_model_id: cifar100_resnet56
