seed: 0
checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  save_top_k: null
  save_last: true
path:
  logdir: .
  checkpoint: ${path.logdir}/model_ckpts/
  dataset: /work/dlclarge2/hoffmaja-pruneshift/datasets
  model: /work/dlclarge2/hoffmaja-pruneshift/models
  imagenet100: ${path.dataset}/ILSVRC2012-100
  imagenet200: null
  imagenet1000: /data/datasets/ILSVRC2012
  deepaugment: /data/datasets/DeepAugment
  renditions: /data/datasets/ImageNet/imagenet-r
loss:
  _target_: pruneshift.losses.StandardLoss
network:
  _target_: pruneshift.networks.create_network
  name: resnet18
  model_path: null
  ckpt_path: null
  version: null
  num_classes: 100
  group: cifar
trainer:
  _target_: pytorch_lightning.Trainer
  gpus: -1
  benchmark: true
  accelerator: ddp
  sync_batchnorm: true
  max_epochs: 100
optimizer:
  _target_: torch.optim.SGD
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0002
  nesterov: true
datamodule:
  name: cifar100
  root: ${path.dataset}
  num_workers: 10
  batch_size: 128
  test_corrupted: true
scheduler:
  _target_: pruneshift.modules.cosine_lr
  T_max: ${trainer.max_epochs}
