# @package checkpoint

_target_: pytorch_lightning.callbacks.ModelCheckpoint
monitor: "val_acc"
save_weights_only: True
dirpath: ${path.logdir}/checkpoint
filename: "{epoch}-{val_acc:.2f}"

mode: "max"
save_top_k: 1

