# @package _global_

datamodule:
    _target_: pruneshift.datamodules.datamodule
    name: cifar100
    root: ${path.dataset}
    num_workers: 10
    batch_size: 128

network:
    _target_: pruneshift.networks.network
    network_id: "cifar100_resnet18"

trainer:
    _target_: pytorch_lightning.Trainer
    max_epochs: 200
    gpus: 1
    benchmark: True

module:
    _target_: pruneshift.modules.VisionModule
    learning_rate: 0.1

scheduler:
    _target_: pruneshift.modules.MultiStepWarmUpLr
    # https://arxiv:org/abs/1708:04552v2:
    milestones: [60, 120, 160]

optimizer:
    _target_: torch.optim.SGD
    momentum: 0.9
    weight_decay: 0.0005
    nesterov: True

seed:
    seed: None
