# @package _global_

path:
    logdir: ${env:EXPERIMENT_PATH}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    config: ${path.logdir}/configs.yaml
    checkpoint: ${path.logdir}/checkpoints/
    dataset: ${env:DATASET_PATH}
    model: ${env:MODEL_PATH}/augmix/
    imagenet100: /misc/scratchSSD2/datasets/ILSVRC2012-100

hydra:
    run:
        dir: ${path.logdir}
