# @package _group_

_target_: pruneshift.networks.create_network
name: resnet50
ckpt_path: ${path.model}/imagenetr_models/deepaugment_and_augmix.pth.tar
imagenet_subset_path: ${datamodule.root}/train
imagenet_path: ${path.imagenet1000}/train
