# @package _group_

_target_: pruneshift.networks.create_network
name: resnext101_32x8d
ckpt_path: /misc/lmbraid19/hoffmaja/models/imagenetr_models/resnext101_augmix_and_deepaugment.pth.tar
imagenet_subset: True

