defaults:
    - path: standard
    - network: standard 
    - datamodule: cifar100
    - trainer: standard

network:
    imagenet_subset: False

datamodule:
    only_test_transforms: True

save_path: ???

seed: 0
train: True
