defaults:
    - hydra/launcher: submitit_slurm
    - checkpoint: last
    - path: standard
    - loss: standard
    - network: pretrained
    - trainer: ddp
    - teacher:
    - optimizer: sgd
    - datamodule: cifar100
    - prune: oneshot

prune:
    method: global_weight
    ratio: null
    amount: 0.5

trainer:
    weights_summary: null

seed: 0
