defaults:
    - checkpoint: last
    - path: standard
    - loss: standard
    - network: pretrained
    - trainer: standard
    - scheduler: cosine
    - teacher: 
    - optimizer: sgd
    - datamodule: cifar100

prune:
    method: global_weight
    ratio: 2

trainer:
    weights_summary: null
    max_epochs: 30

seed: 0

