defaults:
    - checkpoint: only_best
    - path: standard
    - loss: standard
    - network: pretrained
    - trainer: standard
    - scheduler: cosine
    - optimizer: sgd
    - datamodule: cifar100

prune:
    method: global_weight
    ratio: 2

trainer:
    weights_summary: null
    max_epochs: 30

seed: 1234

# Currently we only want to loop over ratios.
hydra:
    sweep:
        dir: ${path.logdir}
        subdir: ratio_${prune.ratio}

