defaults:
    - path: standard
    - checkpoint: only_best
    - regime: cifar10

network:
  model_path: ${path.model}
  version: 0

prune:
  _target_: pruneshift.prune.prune
  method: global_weight
  ratio: 2

# Turn off the weights summary :)
trainer:
  weights_summary: null



