defaults:
    - checkpoint: last
    - path: standard
    - loss: standard
    - network: pretrained
    - trainer: standard
    - scheduler: cosine
    - optimizer: sgd
    - datamodule: cifar100

hydrate:
    ratio: 32

trainer:
    max_epochs: 10
    weights_summary: null

seed: 1234

# Currently we only want to loop over ratios.
# hydra:
#     sweep:
#         dir: ${path.logdir}
#         subdir: ratio_${prune.ratio}

