defaults:
    - checkpoint: last
    - path: standard
    - loss: standard
    - network: pretrained
    - trainer: standard
    - scheduler: cosine
    - optimizer: sgd
    - datamodule: cifar100

hydrate:
    ratio: 4
    method: "weight"

trainer:
    max_epochs: 10
    weights_summary: null

seed: 0

