defaults:
    - hydra/launcher: submitit_slurm
    - checkpoint: period  # This makes a checkpoint at the end of the hydra phase.
    - path: standard
    - loss: standard
    - network: pretrained
    - trainer: ddp 
    - teacher:
    - optimizer: sgd
    - datamodule: cifar100

subnet:
    ratio: null 
    amount: null
    method: "weight"

trainer:
    weights_summary: null

seed: 0
