defaults:
    - hydra/launcher: submitit_slurm
    - checkpoint: last
    - path: standard
    - loss: standard
    - network: pretrained
    - trainer: standard
    - teacher:
    - optimizer: sgd
    - datamodule: cifar100

hydrate:
    ratio: 4
    method: "weight"

trainer:
    weights_summary: null

seed: 0
