defaults:
    - hydra/launcher: submitit_slurm
    - checkpoint: last 
    - path: standard
    - loss: standard
    - network: standard
    - trainer: standard
    - teacher:
    - optimizer: sgd
    - datamodule: cifar100

seed: 0

