defaults:
    - checkpoint: last 
    - path: standard
    - loss: standard
    - network: standard
    - trainer: standard
    - scheduler: cosine
    - optimizer: sgd
    - datamodule: cifar100

seed: 0

